use_frameworks!

def testing_pods
    pod 'Quick', '~> 0.9.0'
    pod 'Nimble', '~> 3.2.0'
end

target 'KakapoTests' do
    testing_pods
end

target 'KakapoExample' do
    pod 'Fakery'
    pod 'SnapKit'
    pod 'SwiftyJSON'
end