use_frameworks!

target 'NewsFeed'

pod 'Kakapo', :path => '../../Kakapo.podspec'
pod 'Fakery', :git => 'https://github.com/PotomacInnovation/Fakery.git', :branch => 'feature/swift3'
pod 'SwiftyJSON', '~> 3.0'
pod 'Alamofire', '~> 4.0'
pod 'SnapKit', '~> 3.0'
pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
