use_frameworks!

target 'NewsFeed'

pod 'Kakapo', :path => '../../Kakapo.podspec'
pod 'Fakery', '~> 1.3'
pod 'SwiftyJSON', '~> 2.3'
pod 'Alamofire', '~> 3.5'
pod 'SnapKit', '~> 0.21'
pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-2.3'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "2.3"
        end
    end
end
