default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :travis do
    scheme = "Kakapo"
    workspace = "KakapoExample/KakapoExample.xcworkspace"

    # Run tests
    scan(
      scheme: scheme,
      workspace: workspace,
      code_coverage: true
    )
  end

end
