default_platform :ios

platform :ios do

  desc "Build and Test"
  lane :travis do
    scheme = "Kakapo"
    workspace = "KakapoExample/KakapoExample.xcworkspace"

    scan(
      scheme: scheme,
      workspace: workspace,
      code_coverage: true
    )
  end

end
